site_name: {{ cookiecutter.project_name }}
docs_dir: docs

plugins:
    - search
    - mermaid2

theme:
  # name: readthedocs
  name: material
  features:
    - navigation.tabs
    - navigation.indexes

  icon:
    # logo: material/book
    logo: divami-logo

  custom_dir: overrides/

markdown_extensions:
  - nl2br
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
extra_css:
  - stylesheets/extra.css